#服务端口
server:
  port: 18080
spring:
  application:
    name: tanhua-app-server
  redis:  #redis配置
    port: 6379
    host: 192.168.10.125
    timeout: 5000
  mail: #发邮件的配置
    default-encoding: UTF-8
    host: smtp.163.com
    password: CTWHBUHGWCQHIOWQ
    port: 465
    properties:
      mail:
        debug: false
        mime:
          splitlongparameters: false
        smtp:
          auth: false
    protocol: smtps
    test-connection: false
    username: yuhao_work1@163.com
  cloud:  #nacos配置
    nacos:
      discovery:
        server-addr: 192.168.10.125:8848
  batch:
    job:
      enabled: false
dubbo:    #dubbo配置
  protocol:
    port: 20880 # dubbo服务端口
    name: dubbo # dubbo服务协议名称
  registry:
    address: nacos://192.168.10.125:8848
  consumer:
    check: false
#tanhua:
#  sms:
#    signName: 物流云商
#    templateCode: SMS_106590012
#    accessKey: LTAI4GKgob9vZ53k2SZdyAC7
#    secret: LHLBvXmILRoyw0niRSBuXBZewQ30la
# ===================================================================
# 分布式文件系统FDFS配置
# ===================================================================
fdfs:
  so-timeout: 1500
  connect-timeout: 600
  #缩略图生成参数
  thumb-image:
    width: 150
    height: 150
  #TrackerList参数,支持多个
  tracker-list: 192.168.10.125:22122
  web-server-url: http://192.168.10.125:8888/
tanhua:
  default:
    recommend:
      users: 2,3,8,10,18,20,24,29,27,32,36,37,56,64,75,88
  oss:
    accessKey: LTAI5tQgnbNQvJ1mGv34qGNG
    secret: LeMKlCtHzjEKqTJnBTqlDjj6lIhGxN
    endpoint: oss-cn-hangzhou.aliyuncs.com
    bucketName: tanhuatanhua111
    url: https://tanhuatanhua111.oss-cn-hangzhou.aliyuncs.com/
  aip:
    appId: 27223159
    apiKey: uquLg0GObdN5P92R1xaNDCB8
    secretKey: p3ptWxdCplCjNH8GGHlBgiZlXsjRX9q8
  huanxin:
    appkey: 1106220909163070#tanhua
    clientId: YXA6frREAFqBQFmPa7H2UX3uVA
    clientSecret: YXA6cylNksxDj5cFp157us4M2rqLNhE
Spring:
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
