server:
  port: 18081
spring:
  application:
    name: tanhua-dubbo-db
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/tanhua?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false
    username: root
    password: 1349502609
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.10.125:8848
dubbo:    #dubbo配置
  protocol:
    port: 20881  # dubbo服务端口
    name: dubbo # dubbo服务协议名称
  registry:
    address: nacos://192.168.10.125:8848
  consumer:
    check: false
  scan:
    base-packages: com.yuhao.api  #dubbo中包扫描

mybatis-plus:
  global-config:
    db-config:
      table-prefix: tb_   # 表名前缀
      id-type: auto   # id策略为自增长